### ISSUE TITLE
Unable to build the volume driver.

### ISSUE THREAD

**Issue by sreeraaman** [quobyte/docker-volume#22] opened 2017-02-28 11:34 UTC
Dear all,

I am trying to build the quobyte docker volume plugin as documented below:

https://github.com/quobyte/docker-volume

When I run the command

$ go get -u github.com/quobyte/docker-volume
I get the following exception.

src/github.com/quobyte/docker-volume/main.go:51: cannot use quobyteID (type string) as type int in argument to handler.Handler.ServeUnix

Can you tell me where I am going wrong.

I tried it with go 1.7 & 1.8 as well.

Best regards
Sriraman.

**Comment by johscheuer** [comment] 2017-02-28 12:11
Hi,

the problem is a change in the docker code base -> https://github.com/docker/go-plugins-helpers/issues/74 I'll have a look and fix it.

You can also use a packaged version from the releases (https://github.com/quobyte/docker-volume/releases)

Best regards,

Johannes

**Comment by sreeraaman** [comment] 2017-02-28 14:16
Hi Johannes ,

Thanks for the quick response. I will give it a shot. However, looking at the contents of the tar.gz file, I could see two folders, bin and the systemd.

Can you please tell me as to which locations these files should be moved to?

best regards
Sriraman.

**Comment by johscheuer** [comment] 2017-02-28 14:19
I assume you are on  a Linux machine (with systemd)? If so just follow these steps https://github.com/quobyte/docker-volume#systemd.

If you have any further questions feel free to ask :)

**Comment by johscheuer** [comment] 2017-02-28 15:06
@sreeraaman building from source should work now :)

I close this issue, feel free to reopen it

**Closed as completed by johscheuer** 2017-02-28 15:06 UTC

**Comment by sreeraaman** [comment] 2017-03-01 04:21
Thank you very much.

best regards
Sriraman.

**Comment by sreeraaman** [comment] 2017-03-02 07:53
Hi,

Tried using the binary tar ball. Now, I am getting the following exception while trying to start the docker-quobyte-plugin via the following command:

systemctl start docker-quobyte-plugin

Exception:

docker-quobyte-plugin.service - Docker Quobyte Plugin
   Loaded: loaded (/usr/lib/systemd/system/docker-quobyte-plugin.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2017-03-02 13:12:09 IST; 11s ago
     Docs: https://github.com/johscheuer/go-quobyte-docker
  Process: 4430 ExecStart=/usr/local/bin/docker-quobyte-plugin --user ${QUOBYTE_API_USER} --password ${QUOBYTE_API_PASSWORD} --api ${QUOBYTE_API_URL} --registry ${QUOBYTE_REGISTRY} (code=exited, status=1/FAILURE)
 Main PID: 4430 (code=exited, status=1/FAILURE)

Mar 02 13:12:09 ip-10-0-0-49.novalocal systemd[1]: Started Docker Quobyte Plugin.
Mar 02 13:12:09 ip-10-0-0-49.novalocal systemd[1]: Starting Docker Quobyte Plugin...
Mar 02 13:12:09 ip-10-0-0-49.novalocal docker-quobyte-plugin[4430]: 2017/03/02 13:12:09 **Scheme is no set in URL: http://10.0.0.49:7860**
Mar 02 13:12:09 ip-10-0-0-49.novalocal systemd[1]: docker-quobyte-plugin.service: main process exited, code=exited, status=1/FAILURE
Mar 02 13:12:09 ip-10-0-0-49.novalocal systemd[1]: Unit docker-quobyte-plugin.service entered failed state.
Mar 02 13:12:09 ip-10-0-0-49.novalocal systemd[1]: docker-quobyte-plugin.service failed.

Can you please advise what could be the issue?

The docker-quobyte-env file is as follows:

QUOBYTE_API_USER=admin
QUOBYTE_API_PASSWORD=quobyte
QUOBYTE_API_URL=http://10.0.0.49:7860
QUOBYTE_REGISTRY=10.0.0.49:7861

best regards
Sriraman.

**Comment by johscheuer** [comment] 2017-03-02 08:15
@sreeraaman you are right this was a stupid bug that was fixed some revisions before. Since we added some improvements to the code base in the last days I created a new release 1.1: 
https://github.com/quobyte/docker-volume/releases/tag/v1.1 (just replace the binary and restart the systemd service)

I tested it and everything works fine. 

like before: If you have any further questions feel free to ask :)

And thanks for your feedback!

**Comment by sreeraaman** [comment] 2017-03-02 12:24
Hi,

I tried will the new release v1.1. Looks like all the services are working. However, I am neither able to list the volumes in docker nor able to create a volume. It takes a long time and then returns back to the command prompt without any response.

Details as follows:

Docker Version : Docker version 1.11.2, build b9f10c9
Centos Version : CentOS Linux release 7.3.1611 (Core)

The following services are running

quobyte-registry
quobyte-api
quobyte-webconsole
docker-quobyte-plugin
docker

I checked the logs under /var/log/quobyte,

It only has logs pertaining to data, metadata, registry, api and webconsole. Nothing on the driver.
Checked the docker logs as well. Nothing fishy.

Checked the volume plugin logs. The last entry says
Mounting Quobyte namespace in /run/docker/quobyte/mnt

Is there anything else that I am missing ?

best regards
Sriraman

**Comment by johscheuer** [comment] 2017-03-02 13:02
Hi @sreeraaman,

I tried it by myself:

```bash
[root@quobyte-client ~]# systemctl status docker-quobyte-plugin
● docker-quobyte-plugin.service - Docker Quobyte Plugin
   Loaded: loaded (/usr/lib/systemd/system/docker-quobyte-plugin.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-02 12:56:43 UTC; 1min 25s ago
     Docs: https://github.com/johscheuer/go-quobyte-docker
 Main PID: 8822 (docker-quobyte-)
   CGroup: /system.slice/docker-quobyte-plugin.service
           ├─8822 /usr/local/bin/docker-quobyte-plugin --user admin --password quobyte --api http://207.154.236.70:7860 --registry 207.154.236.70:7861
           └─8829 /sbin/mount.quobyte 207.154.236.70:7861/ /run/docker/quobyte/mnt -o rw,user_xattr

Mar 02 12:56:43 quobyte-client systemd[1]: Started Docker Quobyte Plugin.
Mar 02 12:56:43 quobyte-client systemd[1]: Starting Docker Quobyte Plugin...
Mar 02 12:56:43 quobyte-client docker-quobyte-plugin[8822]: 2017/03/02 12:56:43 Mounting Quobyte namespace in /run/docker/quobyte/mnt
Mar 02 12:56:57 quobyte-client docker-quobyte-plugin[8822]: 2017/03/02 12:56:57 lstat /run/docker/quobyte/mnt/TestVolume: no such file or directory
Mar 02 12:56:57 quobyte-client docker-quobyte-plugin[8822]: 2017/03/02 12:56:57 Creating volume TestVolume
Mar 02 12:56:57 quobyte-client docker-quobyte-plugin[8822]: 2017/03/02 12:56:57 Validate mounting volume TestVolume on /run/docker/quobyte/mnt/TestVolume

[root@quobyte-client ~]# uname -a
Linux quobyte-client 3.10.0-514.6.1.el7.x86_64 #1 SMP Wed Jan 18 13:06:36 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
[root@quobyte-client ~]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

[root@quobyte-client ~]# docker version
Client:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.11.2
 API version:  1.23
 Go version:   go1.5.4
 Git commit:   b9f10c9
 Built:        Wed Jun  1 21:23:11 2016
 OS/Arch:      linux/amd64
[root@quobyte-client ~]# docker volume ls
DRIVER              VOLUME NAME
quobyte             TestVolume
```

So it works for me.

- What Quobyte Version are you using?
- Can you verify that Quobyte is mounted `grep quobyte /proc/mount`
- Quobyte client is installed 
- Can you verify that you are able to create a Volume over the Web UI?

**Comment by sreeraaman** [comment] 2017-03-02 14:00
Hi,

Sorry to trouble you. This is the output of the commands:

[centos@ip-10-0-0-49 ~]$ grep quobyte /proc/mounts
quobyte@10.0.0.49:7861/ /run/docker/quobyte/mnt fuse rw,nosuid,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other 0 0
[centos@ip-10-0-0-49 ~]$ systemctl status -l docker-quobyte-plugin
â docker-quobyte-plugin.service - Docker Quobyte Plugin
   Loaded: loaded (/usr/lib/systemd/system/docker-quobyte-plugin.service; enabled; vendor preset: disabled)
   Active: active (running) since Thu 2017-03-02 19:18:15 IST; 3min 1s ago
     Docs: https://github.com/johscheuer/go-quobyte-docker
 Main PID: 549 (docker-quobyte-)
   Memory: 79.3M
   CGroup: /system.slice/docker-quobyte-plugin.service
           ââ549 /usr/local/bin/docker-quobyte-plugin --user admin --password quobyte --api http://10.0.0.49:7860 --registry 10.0.0.49:7861
           ââ708 /sbin/mount.quobyte 10.0.0.49:7861/ /run/docker/quobyte/mnt -o rw,user_xattr

Mar 02 19:18:15 ip-10-0-0-49.novalocal systemd[1]: Started Docker Quobyte Plugin.
Mar 02 19:18:15 ip-10-0-0-49.novalocal systemd[1]: Starting Docker Quobyte Plugin...
Mar 02 19:18:15 ip-10-0-0-49.novalocal docker-quobyte-plugin[549]: 2017/03/02 19:18:15 Mounting Quobyte namespace in /run/docker/quobyte/mnt
[centos@ip-10-0-0-49 ~]$

Quobyte version: 1.3.9-2.1

I can create a volume via the web console.

best regards
Sriraman.

**Comment by sreeraaman** [comment] 2017-03-02 14:23
Hi,

Probably I screwed up the installation. Jotting down the steps I did just in case this helps in resolution of the issue.

We have a couple of machines on a private cloud
We are building a DC/OS cluster with 3 Masters, 5 Slaves and 1 Public slave.
We want to run services like cassandra, kafka, spark, jenkins, etc on this cluster via marathon
Since, marathon chooses arbitrary nodes for deploying these services, on service restart, we will lose data.

To ensure that these services do not lose data on service restarts, we wanted a shared storage. That is how we started with quobyte.

Followed the steps as detailed here : https://support.quobyte.com/docs/2/latest/quickstart.html

On all the five slave nodes, I have installed the following:
1. quobyte-server 
2. quobyte-client 
3. ntp

Created two mount points /qmd (metadata) and /qd (data)

On the bootstrap node, have the following services running:
1. quobyte-registry
2. quobyte-api
3. quobyte-webconsole
4. docker-quobyte-plugin

On all the other nodes , have the following services running:

1. quobyte-registry
2. docker-quobyte-plugin

On all the slave nodes, have docker 1.11.2 installed and started.

While deploying the services via marathon, wanted to specify the volume driver as quobyte and
volume name whatever is created specific to the service.

Please correct me if this is not the right approach.

Still not sure what the quobyte-mesos framework does.

best regards
Sriraman

**Comment by johscheuer** [comment] 2017-03-02 15:02
Hi, 

1.) This works for you `qmgmt -u 10.0.0.49:7860 volume create testVolume3 root root BASE 0777`
2.) You also need to run `quobyte-data` and `quobyte-metadata` (Step 3)
3.) I don't know the current limitations of Marathon/Mesos with using Docker Plugin but running the plugin from the normal Docker CLI (https://github.com/quobyte/docker-volume#examples) should work

**Comment by sreeraaman** [comment] 2017-03-03 06:59
Hi,
Followed the steps that you had suggested.

Now, when I try to list volumes using

docker volume ls , I get the following output.

[root@ip-10-0-0-49 ~]# docker volume ls
list quobyte: VolumeDriver.List: open /run/docker/quobyte/mnt: transport endpoint is not connected
DRIVER              VOLUME NAME

Any suggestions as to what could be wrong?. I have about 14 volumes created and all of them appear in the webconsole. I expect the same to be visible here. Am I wrong in my assumptions?

I tried creating a volume via the command:

[root@ip-10-0-0-49 ~]# docker volume create --driver quobyte --name test456

Error response from daemon: create test456: VolumeDriver.Create: RETRY_OTHER_IMMEDIATELY/POSIX_ERROR_NONE: database dirdb not found /
[root@ip-10-0-0-49 ~]#
